//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SriArungaraiAmmanTraders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int Sales_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
